/*
 * Delegate Runner
 *
 * This is the API for Delegate Runner
 *
 * API version: 1.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type ProxySetting struct {

	HttpProxy string `json:"httpProxy,omitempty"`

	HttpsProxy string `json:"httpsProxy,omitempty"`

	NoProxy bool `json:"noProxy,omitempty"`
}
