/*
 * Delegate Runner
 *
 * This is the API for Delegate Runner
 *
 * API version: 1.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Volume struct {

	EmptyDir *EmptyDir `json:"emptyDir,omitempty"`

	HostPath *HostPath `json:"hostPath,omitempty"`
}
