/*
 * Delegate Runner
 *
 * This is the API for Delegate Runner
 *
 * API version: 1.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type HostPath struct {

	VolumeId string `json:"volumeId,omitempty"`

	Name string `json:"name,omitempty"`

	Path string `json:"path,omitempty"`

	Labels map[string]string `json:"labels,omitempty"`
}
