/*
 * Delegate Runner
 *
 * This is the API for Delegate Runner
 *
 * API version: 1.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Secret struct {

	Id string `json:"id,omitempty"`

	Data string `json:"data,omitempty"`

	Mask bool `json:"mask,omitempty"`
}
