/*
 * Delegate Runner
 *
 * This is the API for Delegate Runner
 *
 * API version: 1.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type File struct {

	Path string `json:"path,omitempty"`

	Mode string `json:"mode,omitempty"`

	Data string `json:"data,omitempty"`

	IsDir bool `json:"isDir,omitempty"`
}
