/*
 * Delegate Runner
 *
 * This is the API for Delegate Runner
 *
 * API version: 1.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type ResourcePoolIdentifier struct {
	// allocate execution infrastructure from the resource pool identified by \"id\".
	Id string `json:"id,omitempty"`
	// allocate execution infrastructure from the fallback pools when the one identified by \"id\" does not work.
	FallbackIds []string `json:"fallbackIds,omitempty"`
}
