/*
 * Delegate Runner
 *
 * This is the API for Delegate Runner
 *
 * API version: 1.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type LogConfig struct {

	Url string `json:"url,omitempty"`

	LogKey string `json:"logKey,omitempty"`

	Token string `json:"token,omitempty"`
	// Whether to directly upload via signed link or using log stream service
	IndirectUpload bool `json:"indirectUpload,omitempty"`
}
