/*
 * Delegate Runner
 *
 * This is the API for Delegate Runner
 *
 * API version: 1.0.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models


type ExecutionInfrastructure struct {

	ProjectId string `json:"projectId,omitempty"`

	OrgId string `json:"orgId,omitempty"`

	AccountId string `json:"accountId,omitempty"`

	PipelineId string `json:"pipelineId,omitempty"`

	StageId string `json:"stageId,omitempty"`
	// id of the statemachine entity from harness delegate
	CorrelationId string `json:"correlationId,omitempty"`
	// From which path to execute commands
	WorkDir string `json:"workDir,omitempty"`

	InfraType string `json:"infraType,omitempty"`

	Pool *ResourcePoolIdentifier `json:"pool,omitempty"`
	// tags applied to the execution infrastructure being created.
	Tags map[string]string `json:"tags,omitempty"`

	LogConfig *LogConfig `json:"logConfig,omitempty"`

	ProxySetting *ProxySetting `json:"proxySetting,omitempty"`

	Volumes []Volume `json:"volumes,omitempty"`

	Files []File `json:"files,omitempty"`

	Secrets []Secret `json:"secrets,omitempty"`
	// additional key-value attributes
	Attributes map[string]string `json:"envs,omitempty"`

	Envs map[string]string `json:"envs,omitempty"`
}
